POST http://localhost:9000/pets
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE3MjMzYzMxYTNkNjUwMTcyYzhmMDYiLCJuYW1lIjoiUmFmYWVsIiwiZW1haWwiOiJmdWxlY28ucmEucGhhQGdtYWlsLmNvbSIsInBhc3N3ZCI6IiQyYiQxMCQ4OG5CWTEzWE14bFI3MUdMOEtBUjBlZ2dSRDBaZHlqcXhCRG5SNHNwTy43czhIWkxTV3ljcSIsInBlcm1pc3Npb24iOiJ1c2VyIiwiYWRkcmVzcyI6IlJ1YSBkYXMgUm9zYXMgMjU1IiwicGhvbmUiOiIoNzkpOSA4ODQ0LTM4ODUiLCJfX3YiOjAsImlhdCI6MTU5NTQ0MjI2OSwiZXhwIjoxNTk1NDQ0MDY5fQ.Ieay7I4dh9zDFAjvIQpQFW126W5Z6Ye0SCLBhyAphBM
refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE3MjMzYzMxYTNkNjUwMTcyYzhmMDYiLCJuYW1lIjoiUmFmYWVsIiwiZW1haWwiOiJmdWxlY28ucmEucGhhQGdtYWlsLmNvbSIsInBhc3N3ZCI6IiQyYiQxMCQ4OG5CWTEzWE14bFI3MUdMOEtBUjBlZ2dSRDBaZHlqcXhCRG5SNHNwTy43czhIWkxTV3ljcSIsInBlcm1pc3Npb24iOiJ1c2VyIiwiYWRkcmVzcyI6IlJ1YSBkYXMgUm9zYXMgMjU1IiwicGhvbmUiOiIoNzkpOSA4ODQ0LTM4ODUiLCJfX3YiOjAsImlhdCI6MTU5NTQ0MTkxNX0.hfxtYX-v3uA_JVYGEeijJI6vyrvRGfLLYH6UugPMEtQ

{
  "client": "5f17233c31a3d650172c8f06",
  "name": "Milicuco",
  "age": 11,
  "type": "Cat",
  "breed": "Snow Boots",
  "image": "cat.png"
}

###

POST http://localhost:9000/pets
Content-Type: application/json

{
  "client": "5f17233c31a3d650172c8f06",
  "name": "Milicuco",
  "age": 10,
  "image": "cat.png"
}

###

GET http://localhost:9000/pets/client
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE3MjMzYzMxYTNkNjUwMTcyYzhmMDYiLCJuYW1lIjoiUmFmYWVsIiwiZW1haWwiOiJmdWxlY28ucmEucGhhQGdtYWlsLmNvbSIsInBhc3N3ZCI6IiQyYiQxMCQ4OG5CWTEzWE14bFI3MUdMOEtBUjBlZ2dSRDBaZHlqcXhCRG5SNHNwTy43czhIWkxTV3ljcSIsInBlcm1pc3Npb24iOiJ1c2VyIiwiYWRkcmVzcyI6IlJ1YSBkYXMgUm9zYXMgMjU1IiwicGhvbmUiOiIoNzkpOSA4ODQ0LTM4ODUiLCJfX3YiOjAsImlhdCI6MTU5NTQ0MjI2OSwiZXhwIjoxNTk1NDQ0MDY5fQ.Ieay7I4dh9zDFAjvIQpQFW126W5Z6Ye0SCLBhyAphBM
refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE3MjMzYzMxYTNkNjUwMTcyYzhmMDYiLCJuYW1lIjoiUmFmYWVsIiwiZW1haWwiOiJmdWxlY28ucmEucGhhQGdtYWlsLmNvbSIsInBhc3N3ZCI6IiQyYiQxMCQ4OG5CWTEzWE14bFI3MUdMOEtBUjBlZ2dSRDBaZHlqcXhCRG5SNHNwTy43czhIWkxTV3ljcSIsInBlcm1pc3Npb24iOiJ1c2VyIiwiYWRkcmVzcyI6IlJ1YSBkYXMgUm9zYXMgMjU1IiwicGhvbmUiOiIoNzkpOSA4ODQ0LTM4ODUiLCJfX3YiOjAsImlhdCI6MTU5NTQ0MTkxNX0.hfxtYX-v3uA_JVYGEeijJI6vyrvRGfLLYH6UugPMEtQ

###

GET http://localhost:9000/pets/5f18841e4c0d205a72f26f9c
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE3MjMzYzMxYTNkNjUwMTcyYzhmMDYiLCJuYW1lIjoiUmFmYWVsIiwiZW1haWwiOiJmdWxlY28ucmEucGhhQGdtYWlsLmNvbSIsInBhc3N3ZCI6IiQyYiQxMCQ4OG5CWTEzWE14bFI3MUdMOEtBUjBlZ2dSRDBaZHlqcXhCRG5SNHNwTy43czhIWkxTV3ljcSIsInBlcm1pc3Npb24iOiJ1c2VyIiwiYWRkcmVzcyI6IlJ1YSBkYXMgUm9zYXMgMjU1IiwicGhvbmUiOiIoNzkpOSA4ODQ0LTM4ODUiLCJfX3YiOjAsImlhdCI6MTU5NTQ0MjI2OSwiZXhwIjoxNTk1NDQ0MDY5fQ.Ieay7I4dh9zDFAjvIQpQFW126W5Z6Ye0SCLBhyAphBM
refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE3MjMzYzMxYTNkNjUwMTcyYzhmMDYiLCJuYW1lIjoiUmFmYWVsIiwiZW1haWwiOiJmdWxlY28ucmEucGhhQGdtYWlsLmNvbSIsInBhc3N3ZCI6IiQyYiQxMCQ4OG5CWTEzWE14bFI3MUdMOEtBUjBlZ2dSRDBaZHlqcXhCRG5SNHNwTy43czhIWkxTV3ljcSIsInBlcm1pc3Npb24iOiJ1c2VyIiwiYWRkcmVzcyI6IlJ1YSBkYXMgUm9zYXMgMjU1IiwicGhvbmUiOiIoNzkpOSA4ODQ0LTM4ODUiLCJfX3YiOjAsImlhdCI6MTU5NTQ0MTkxNX0.hfxtYX-v3uA_JVYGEeijJI6vyrvRGfLLYH6UugPMEtQ


###

PUT http://localhost:9000/pets/5f16e34ce5f71823e4e095be
Content-Type: application/json

{
  "age": 11
}

###

DELETE http://localhost:9000/pets/5f16e34ce5f71823e4e095be