POST http://localhost:9000/products
Content-Type: application/json

{
  "title": "Ração pra Gato Whiskas Deluxe",
  "slug": "racao-wiskas-deluxe-gato",
  "description": "Ração feita com as malhores carnes do mercado para seu amiguinho",
  "price": 79.99,
  "tags": ["Gato", "Comida", "Ração", "Bichano", "Whiskas"]
}

###

POST http://localhost:9000/products
Content-Type: application/json

{
  "title": "Ração pra Gato Whiskas Deluxe",
  "description": "Ração feita com as malhores carnes do mercado para seu amiguinho",
  "tags": ["Gato", "Comida", "Ração", "Bichano", "Whiskas"]
}

###

GET http://localhost:9000/products

###

GET http://localhost:9000/products/slug/racao-wiskas-deluxe-gato

###

GET http://localhost:9000/products/id/5f0ccd6e4ee9f950e33a41f7

###

GET http://localhost:9000/products/tag/whiskas

###

GET http://localhost:9000/products/tag/whis

###

PUT http://localhost:9000/products/5f0ccd6e4ee9f950e33a41f7
Content-Type: application/json

{
  "title": "Ração Gato Whiskas Deluxe"
}

###

DELETE http://localhost:9000/products/5f0ccd6e4ee9f950e33a41f7
